name = 'render_target_p1.fs'
uuid = 'bbef1914-e0c3-48ce-9866-eb46a3a2353d'

[[resources]]
type = 'Bytes'
name = 'render_target_p1.fs'
uuid = '2e76fdc1-8fae-4957-8231-cbc3acaa452a'

[params]
type = 'Bytes'
