name = 'render_target_p1.vs'
uuid = 'e8d497e1-36a2-4853-b388-aa9c18098ab5'

[[resources]]
type = 'Bytes'
name = 'render_target_p1.vs'
uuid = 'c0685052-00db-4c85-81e9-c2bceab81da6'

[params]
type = 'Bytes'
