name = 'texture.png'
uuid = '45d19482-65fd-46c2-8efd-eb1064d263a2'

[[resources]]
type = 'Texture'
name = 'texture.png'
uuid = 'f22c83c0-b7a3-468d-b134-03971ab04402'

[params]
type = 'Texture'
mipmap = true
alpha_premultiply = false
wrap = 'Clamp'
filter = 'Linear'
compression = 'HighQuality'
