[package]
name = "crayon-examples"
version = "0.1.0"
authors = ["Jingkai Mao <oammix@gmail.com>"]

[badges]
travis-ci = { repository = "shawnscode/crayon", branch = "master" }

[dependencies]
rand = "0.3.18"
image = "0.18.0"
crayon = { path = "..", version = "0.1.0" }
crayon-imgui = { path = "../modules/imgui", version = "0.1.0" }